config/routes.rb
Rails.application.routes.draw do
    # Checkpoint #46 - Comments
    #
    # Nest the comments resource under 'resources :post's in 'routes.rb.'' You
    # only have one comment action for now, create, so only create the routes
    # that you need.
    #
    # Hint: Use only: instead of except.
    #
    # By nesting comments inside of 'posts', they'll be nested inside 'topics'
    # as well. As the 'create' url, '/topics/:topic_id/posts/:post_id/comments',
    # suggests, this "deep nesting" can get complicated, and we should refactor
    # it.
    #
    # Commmented out this next line, since keeping it forms a redundancy with
    # the 'resources :comments, only: [:new, :create]' statement below.
    # get 'comments/:new'

  devise_for :users
  
  # Checkpoint #41 - Interlude
  #
  # To make changing user's name possible, we've added a second form under the
  # "Edit personal information" heading. To make it work we also need to modify
  # the routes and make a dedicated UsersController. Open config/routes.rb file
  # and add the following line below the devise_for :users line.
  
  # Checkpoint #58 - Public Profiles
  #
  # You'll only run into this error (the routing error generated afer initially creating 'profiles_spec.rb) if you have resources :users, only: [:update] in your routes file. If you just have resources :users, don't worry if you didn't see the above.
  #resources :users, only: [:update]
  #
  # Checkpoint #59 - Popular Posts
  #
  # While we're thinking about popular posts, let's build a way to display the top Bloccit users.
  #
  #resources :users, only: [:show, :update]
  resources :users, only: [:show, :update, :index]
  
  # Checkpoint #33 - CRUD
  #
  # "We'll remove those in favor of a more succinct way of creating 'Post'
  # routes. Call the 'resources' method, and pass it a sybmol. By doing this
  # you instruct Rails to create routes for every CRUD action."
  #
  # get 'posts/index'
  # get 'posts/show'
  # get 'posts/new'
  # get 'posts/edit'

  # Mentor feedback:
  #   Delete line 15 (posts are nested under topics now).
  #
  # Question: Why does not the checkpoint explicitly remove or comment out
  # 'resources :posts'?
  #
  # resources :posts
  
  # Checkpoint #40 - Topics and Posts
  #
  # The four statements below were automatically generating by the following
  # command executed in the IRB:
  #
  #     'rails g controller topics index new show edit'
  #
  # get 'topics/index'
  # get 'topics/new'
  # get 'topics/show'
  # get 'topics/edit'
  #
  # However, these are commented out in favor of the shortcut that follows.
  # resources :topics
  # By calling 'resources :posts' in the 'resources :topics' block, you are
  # instructing Rails to create nested routes. Review your new routes by
  # running 'rake routes | grep post'.
  # resources :topics do
    # resources :posts, except: [:index]
    #
    # Checkpoint #46 - Comments
    #
    # Nest the comments resource under 'resources :post's in 'routes.rb.'' You
    # only have one comment action for now, create, so only create the routes
    # that you need.
    #
    # Hint: Use only: instead of except.
    #
    # By nesting comments inside of 'posts', they'll be nested inside 'topics'
    # as well. As the 'create' url, '/topics/:topic_id/posts/:post_id/comments',
    # suggests, this "deep nesting" can get complicated, and we should refactor
    # it.
    # resources :posts, except: [:index] do
      # Checkpoint #51 - Destroy
      #
      # Go back to localhost and try to delete a comment. Did you receive an error? (You should have!) If so, try to troubleshoot it on your own before reading on.
      #
      # The error was raised because you have not created a proper route for destroying comments. Open 'routes.rb' and modify the 'resources :comments' declaration to include 'destroy'.
      #
      # resources :comments, only: [:create]
      #resources :comments, only: [:create, :destroy]
    # end
    
    # Assignment #51 - Destroy
    #
    # As the Rails Guide to Routing makes clear, deep route nesting can "quickly become cumbersome". It is cumbersome in a number of ways:
    #
    # - In 'CommentsController' we separately initialize '@topic', '@post' and '@comment'. We do so because the IDs are in the params hash. However, this is unnecessary because we can find the topic and post from the comment. Furthermore, what would happen if we navigated to '/topics/:topic_id/posts/:id' where the post does not belong to the topic? What would happen if we deleted one of the post's comments?
    #
    # - Our routing is cumbersome. In order to route to a comment, we have to know and reference its parent post and topic.
    #
    # - We nested our routes too deeply. As a result, our path helpers are confusing. Before, we just had post_path, but now we have '[@topic, @post, comment]'', or its unintuitive route, 'topic_post_comment_path'.
    #
    # To solve these issues, implement "shallow nesting".
    #
    # Change your routes file to reflect only the primary relationships.
    #
    # Note the 'only: []'' in the top-level post resources line. This is because we don't want to create any '/posts/:id' routes, just 'posts/:post_id/comments'.
  # end
    resources :topics do
      # Checkpoint #59 - Popular Posts
      #
      # Let's move our post views and controllers so they're nested under topics. Make the following directory changes:
      #   - app/controllers/posts_controller.rb -> app/controllers/topics/posts_controller.rb
      #   - app/views/posts/_form.html.erb -> app/views/topics/posts/_form.html.erb
      #   - app/views/posts/edit.html.erb -> app/views/topics/posts/edit.html.erb
      #   - app/views/posts/new.html.erb -> app/views/topics/posts/new.html.erb
      #   - app/views/posts/show.html.erb -> app/views/topics/posts/show.html.erb
      #
      #resources :posts, except: [:index]
      resources :posts, except: [:index], controller: 'topics/posts'
    end
    
    # Checkpoint #59 - Popular Posts
    #
    # The '/app/controllers/posts_controller.rb' 'index' action and the 'app/views/posts/index.html.erb' view combination does not have a route -- let's add it. Because we already have a top-level :posts resource -- without any actions -- we can just add :index to that resource declaration.
    #
    #resources :posts, only: [] do
    resources :posts, only: [:index] do
      resources :comments, only: [:create, :destroy]

      # Checkpoint #55 - Favoriting
      #
      # Notice we didn't specify any views - that is because this controller won't have any normal views. We'll define create and destroy actions, which aren't associated with GET requests, and so have no views. Add the required routes for create and destroy to routes.rb.
      resources :favorites, only: [:create, :destroy]
      
      # Checkpoint #53 - Voting
      #
      # In the voter partial, we stubbed out the destination URL in the link_to methods, but obviously we'll need to update this so the vote links actually do something. Votes are different than topics or posts, because they do not need a complete RESTful resource. In other words, there are no forms or specific views for votes, only the links in the voter partial. This means that our best option is to create a couple of routes manually in 'routes.rb'.
      #
      # These lines set up POST routes at the URL 'posts/:id/up-vote' and 'posts/:id/down-vote'. The as key-value pairs at the end stipulate the method names which will be associated with these routes: 'up_vote_path' and 'down_vote_path'.
      post 'up/vote' => 'votes#up_vote', as: :up_vote
      post 'down/vote' => 'votes#down_vote', as: :down_vote
    end
    
  # Checkpoint #33 - CRUD
  #
  # "Notice that we also removed the get 'welcome/index', because we've
  # declared the 'index' view as 'root'. We also cleaned up the 'about'
  # route, by allowing a user to type '/about' rather than /welcome/about'."
  #
  # get 'welcome/index'
  get 'about' => 'welcome#about'
  
  # I commented this out, since it did not appear in this checkpoint.
  # get 'welcome/contact'
  
  root to: 'welcome#index'
end

app/controllers/topics/posts_controller.rb
# Checkpoint #59 - Popular Posts
#
# Since we've moved the posts controller under topics and changed the routes, we'll need to modify the class declaration in app/controllers/topics/posts_controller.rb.
#
# Topics::PostsController instructs the controller where to find the appropriate views to invoke. See the Admin::UserPermissions example in the Rails Guide we linked to above.
#
#class PostsController < ApplicationController
class Topics::PostsController < ApplicationController
  # Checkpoint #40 - Topics and Posts
  #
  # From 'routes.rb':
  #     However, these are commented out in favor of the shortcut that follows.
  #     resources :topics
  #     By calling 'resources :posts' in the 'resources :topics' block, you are
  #     instructing Rails to create nested routes. Review your new routes by
  #     running 'rake routes | grep post'.
  #
  #     resources :topics do
  #       resources :posts, except: [:index]
  #     end
  #
  # You may notice that there's no long a Post route for 'index'. This is
  # because the 'posts/index.html.erb' is no longer needed. All posts will be
  # displayed with respect to a Topic now, so 'posts#index' serves no purpose.
  # Remove the 'index' action from the 'posts_controller.rb', and delete
  # 'app/views/posts/index.html.erb'. You can remove it and stage the removal
  # at once by typing 'git rm app/views/posts/index.html.erb'.
  #
=begin  
  #def index
    # Checkpoint #33 - CRUD
    #
    # "To show dynamic data from the Bloccit database, you'll need to modify
    # the 'index' method in 'post_controller.rb'. In the 'posts_controller.rb',
    # add the following to the 'index' method."
    @posts = Post.all
    
    # Checkpoint #39 - Authorization
    authorize @posts
  end
=end

  def show
    # Checkpoint #46 - Comments
    #
    # View changes:
    #   - You'll need to show comments associated with a post, so modify the
    #     posts_controller to provide the requisite instance variable to
    #     'posts/show.html.erb'.
    #@comment = @post.comments.find(params[:id])

    # Checkpoint #33 - CRUD
    #
    # "...before we update the view, let's go back to 'posts_controller.rb" and
    # update the 'show' method:"
    #
    # The 'show' method declares an instance variable names '@post' and assigns
    # it to the return of 'Post.find(params[:id])'. As you saw before, the
    # 'find' method is an Active Record method that takes an object 'id' as an
    # argument.
    #
    # "The 'PostsController' does not automatically know which post a user
    # clicked. This information has to be extracted from the request made when
    # the link was clicked. Rails controllers parse this request information
    # into a 'params' hash available in the controller and its associated
    # views."
    #
    
    # Checkpoint #40 - Topics and Posts
    #
    # In 'app/views/posts/show.html.erb' we have the statement
    #
    #     '<%= link_to "Edit", edit_topic_post_path(@topic, @post), class: 'btn btn-success' %>'
    #
    # '@topic' is being used to generate a valid URL, but that variable does
    # not exist yet in this view. We add the '@topic' variable here.
    @topic = Topic.find(params[:topic_id])
    
    # Checkpoint #46 - Comments
    #
    # Given the nesting structure, change this here to reflect the following
    # URL: '/topics/:topic_id/posts/:post_id/comments'
    #
    # @post = Post.find(params[:id])
    @post = @topic.posts.find(params[:id])
    @comment = Comment.new
    @comments = @post.comments
  end
  
  def create
    # Checkpoint #40 - Topics and Posts
    @topic = Topic.find(params[:topic_id])
    
    # Checkpoint #41 - Interlude
    #
    # Apply DRY.
    # @post = Post.new(params.require(:post).permit(:title, :body))
    @post = Post.new(post_params)
    
    # Checkpoint #38 - Associations
    @post.user = current_user
    
    # Checkpoint #40 - Topics and Posts
    @post.topic = @topic
    
    # Checkpoint #39 - Authorization
    # 
    # We need to restrict 'posts#create', for when the 'posts#new' form is
    # submitted. We use 'authorize()' to check restrictions on the '@post'
    # about to be saved.
    authorize @post
    
    # Checkpoint #35 - More CRUD
    # raise # This will short-circuit the method
    if @post.save
      # Checkpoint #54 - Mocking with RSpec
      #
      # Anywhere we create a post, we must also call create_vote on it. Some simple text searching for Post.create and post.save returns two relevant results outside of our specs, the posts_controller and our seeds file.
      @post.create_vote
      
      flash[:notice] = "Post was saved."
      
      # Checkpoint #40 - Topics and Posts
      #
      # redirect_to @post
      redirect_to [@topic, @post]
    else
      flash[:error] = "There was an error saving the post. Please try again."
      render :new
    end
  end

  def new
    # Checkpoint #40 - Topics and Posts
    @topic = Topic.find(params[:topic_id])
    @post = Post.new
    @comment = @post.comments
    
    # Checkpoint #39 - Authorization
    #
    # 'authorize()' will check the policy on new post resources. If it's
    # satisfied (in this case, if a user is present), it will let the
    # rendering continue. If not (if no user is present), it'll throw an
    # exception.
    #
    # We have access to this 'authorize' method because we included 'Pundet'
    # in 'ApplicationController', from which the 'PostController' inherits.
    authorize @post
    
    # Assignment #46 - Comments
    #
    # If you try to create a comment without first signing in, you'll encounter a no method 'id' for NilClass error. This error is thrown because current_user is nil when you're not signed in, and comment creation attempts to extract an id from this nil object.
    #   - Use CommentPolicy in PostsController and CommentsController to authorize your comments.
    authorize @comment
  end

  def edit
    # Checkpoint #40 - Topics and Posts
    @topic = Topic.find(params[:topic_id])
    
    # Checkpoint #35 - More CRUD
    @post = Post.find(params[:id])
    
    # Checkpoint #39 - Authorization
    #
    # Call authorize after the objects you've authorized have been defined.
    authorize @post
  end
  
  def update
    # Checkpoint #35 - More CRUD
    @post = Post.find(params[:id])
    @topic = Topic.find(params[:topic_id])
    
    # Checkpoint #39 - Authorization
    #
    # Call authorize after the objects you've authorized have been defined.
    authorize @post
    
    # Checkpoint #41 - Interlude
    #
    # Apply DRY.
    # if @post.update_attributes(params.require(:post).permit(:title, :body))
    if @post.update_attributes(post_params)
      flash[:notice] = "Post was updated."
      redirect_to [@topic, @post]
    else
      flash[:error] = "There was an error saving the post. Please try again."
      render :edit
    end
  end
  
  # Checkpoint #51 - Destroy
  #
  # Open PostsController and add a destroy action
  def destroy
    @topic = Topic.find(params[:topic_id])
    @post = Post.find(params[:id])
    
    authorize @post
    
    if @post.destroy
      flash[:notice] = "\"#{@post.title}\" was deleted successfully."
      redirect_to @topic
    else
      flash[:error] = "There was an error deleting the post."
      render :show
    end
  end

  # Checkpoint #41 - Interlude
  #
  # Apply DRY.
  private

  def post_params
    params.require(:post).permit(:title, :body)
  end
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/views/topics/_form.html.erb
<!--
    Assignment #42 - Validating Posts

    Create a form partial for topics.
-->
<%= form_for topic do |f| %>
    <% if topic.errors.any? %>
        <div class="alert alert-danger">
            <h4>There are <%= pluralize(topic.errors.count, "error") %>.</h4>
            <ul>
                <%= topic.errors.full_messages.each do |msg| %>
                    <li><%= msg %></li>
                <% end %>
            </ul>
        </div>
    <% end %>
    <!--
        Assignment #42 - Validating Posts
        
        Use the form_group_tag helper method created in the checkpoint to
        display errors for invalid topics.
    -->
    <%= form_group_tag(topic.errors[:name]) do %>
        <%= f.label :name %>
        <%= f.text_field :name, class: 'form-control', placeholder: "Enter topic name" %>
    <% end %>
    <div class="form-goup">
        <%= f.submit "Save", class: 'btn btn-success'%>
    </div>

    <%= render partial: 'form', locals: { topic: @topic } %>
<% end %>

app/views/topics/edit.html.erb
<!--
    Checkpoint #40 - Topics and Posts
    The Topics controller file was created by executing the following statement
    in the IRB:
         'rails g controller topics index new show edit'
<h1>Topics#edit</h1>
<p>Find me in app/views/topics/edit.html.erb</p>
-->
<h1>Edit Topic</h1>

<div class="row">
    <div class="col-md-4">
        <p>Guidelines for topics:</p>
        <ul>
            <li>Make sure the topic is appropriate.</li>
            <li>Never insult dogs.</li>
            <li>Smile when you type.</li>
        </ul>
    </div>
    <div class="col-md-8">
        <!--
            Assignment #42 - Validating Posts
            
            Create a form partial for topics.

        &lt;%= form_for @topic do |f| %&gt;
            <div class="form-group">
                &lt;%= f.label :name %&gt;
                &lt;%= f.text_field :name, class: 'form-control', placeholder: "Enter topic name" %&gt;
            </div>
            <div class="form-group">
                &lt;%= f.label :description %&gt;
                &lt;%= f.text_area :description, rows: 8, class: 'form-control', placehoder: "Enter topic description" %&gt;
            </div>
            <div class="form-group">
                &lt;%= f.label :public, class: 'checkbox' do %&gt;
                    &lt;%= f.check_box :public %&gt; Public topic
                &lt;% end %&gt;
            </div>
            &lt;%= f.submit "Save", class: 'btn btn-success' %&gt;
        &lt;% end %&gt;
        -->        
        <%= render partial: 'form', locals: { topic: @topic } %>
    </div>
</div>

app/views/topics/index.html.erb
<!--
    Checkpoint #40 - Topics and Posts
    The Topics controller file was created by executing the following statement
    in the IRB:
         'rails g controller topics index new show edit'
Update the views that were created by the controller generator, starting with
'topics/index.html.erb'. We still want to maintain proper authorization, so
we'll wrap the "New Topic" link in an 'if policy()'.
<h1>Topics#index</h1>
<p>Find me in app/views/topics/index.html.erb</p>
-->
<h1>Topics</h1>

<div class="row">
    <div class="col-md-8">
        <% @topics.each do |topic| %>
            <div class="media">
                <div class="media-body">
                    <h4 class="media-heading">
                        <%= link_to topic.name, topic %>
                    </h4>
                    <small>
                        <%= topic.description %>
                    </small>
                </div>
            </div>
        <% end %>
        
        <!--
            Checkpoint #45 - Pagination
            
            Now that our controller is generating a collection of paginated
            topics let's modify the index view to display them. Open
            'app/views/topics/index.html.erb' and add the line of code with
            'will_paginate'.
            
            This line creates the visual interface for turning pages. As you can
            tell if you remove it, your resource collection will still be
            limited to the number of objects specified in the paginate call in
            your controller. You can still navigate pages by updating the URL
            query string.
        -->
        <%= will_paginate @topics %>
    </div>
    <div class="col-md-4">
        <% if policy(Topic.new).create? %>
            <%= link_to "New Topic", new_topic_path, class: 'btn btn-success' %>
        <% end %>
    </div>
</div>

app/views/topics/new.html.erb
<!--
    Checkpoint #40 - Topics and Posts
    The Topics controller file was created by executing the following statement
    in the IRB:
         'rails g controller topics index new show edit'
<h1>Topics#new</h1>
<p>Find me in app/views/topics/new.html.erb</p>
-->
<h1>New Topic</h1>

<div class="row">
    <div class="col-md-4">
        <p>Guidelines for topics:</p>
        <ul>
            <li>Make sure the topic is appropriate.</li>
            <li>Never insult dogs.</li>
            <li>Smile when you type.</li>
        </ul>
    </div>
    <div class="col-md-8">
        <!--
            Assignment #42 - Validating Posts
            
            Create a form partial for topics.

        &lt;%= form_for @topic do |f| %&gt;
            <div class="form-group">
                &lt;%= f.label :name %&gt;
                &lt;%= f.text_field :name, class: 'form-control', placeholder: "Enter topic name" %&gt;
            </div>
            <div class="form-group">
                &lt;%= f.label :description %&gt;
                &lt;%= f.text_area :description, rows: 8, class: 'form-control', placeholder: "Enter topic description" %&gt;
            </div>
            <div class="form-group">
                &lt;%= f.label :public, class: 'checkbox' do %&gt;
                    &lt;%= f.check_box :public %&gt; Public topic
                &lt;% end %&gt;
            </div>
            &lt;%= f.submit "Save", class: 'btn btn-success' %&gt;
        &lt;% end %&gt;
        -->
        
        <%= render partial: 'form', locals: { topic: @topic } %>
    </div>
</div>

app/views/topics/show.html.erb
<!--
    Checkpoint #40 - Topics and Posts
    The Topics controller file was created by executing the following statement
    in the IRB:
         'rails g controller topics index new show edit'
<h1>Topics#show</h1>
<p>Find me in app/views/topics/show.html.erb</p>
-->
<h1><%= @topic.name %></h1>

<% if policy(@topic).update? %>
    <%= link_to "Edit Topic", edit_topic_path, class: 'btn btn-success' %>
<% end %>

<div class="row">
    <div class="col-md-8">
        <p class="lead"><%= @topic.description %></p>
        <!--
            Checkpoint #58 - Public Profiles
            
            Make sure to modify the reference to @topic, changing it to post.topic, so the partial can be included in pages that don't have a @topic variable.
            
            Render it from topics#show, using Rails's collection rendering shortcut.
            
        % @posts.each do |post| %>
            <!--
                Checkpoint #58 - Public Profiles

                Our profile pages would look better with a list of formatted links to posts, rather than displaying post titles. This is identical to what we do on the topics#show page, so rather than repeat that HTML, let's move that code into a partial that can be rendered from both pages.

                In the topics#show view, cut everything within the @posts.each block and paste it into a new app/views/posts/_post.html.erb partial.

            <div class="media">
                <!--
                    Checkpoint #53 - Voting
                    
                    The 'app/views/topics/show.html.erb' view should render the voter partial as well. Users may appreciate being able to vote on posts without drilling all the way to the actual post view. Open 'app/views/topics/show.html.erb' and add the render call.
                    
                    Because our voter partial is DRY and modular, no other change is needed. Check out this new view in localhost.
                
                %= render partial: 'votes/voter', locals: { post: post } %>
                <div class="media-body">
                    <h4 class="media-heading">
                        <!--
                            Checkpoint #40 - Topics and Posts
                            
                            Looking at our 'rake routes' output, how do you
                            think this path helper needs to change? If you
                            guessed '&lt;= link_to post.title,
                            topic_post_path(@topic, post) %&gt;' you're
                            correct. But we'll actually see sometihng more
                            idiomatic and similar to our previous
                            'lt;%= link_to post.title, post %gt;'.
                            &lt;%= link_to post.title, post %&gt;
                        -->
                        <!--
                            Checkpoint #40 - Topics and Posts
                            
                            Remember, even though you didn't explicitly
                            declare 'topic_post_path', Rails extracts it
                            from the '@topic' and 'post' in this example.
                            This is yet another example of Rails
                            conventions. If this "Rails magic" still
                            doesn't make sense, please consult with your
                            mentor.
                        -->
                        <!--
                            Checkpoint #43 - Post Markdown
                            
                        &lt;%= link_to post.title, [@topic, post] %&gt;
                        
                        %= link_to (markdown_to_html post.title), [@topic, post] %>
                    </h4>
                    
                    <!--
                        Checkpoint #44 - Uploading Images
                        
                        Let's make a similar change to topics#show as was done
                        with posts#show, so that each related post is associated
                        with its user's image.

                    <small>
                        submitted &lt;%= time_ago_in_words(post.created_at) %&gt; ago by &lt;%= post.user.name %&gt;<br />
                    </small>
                    
                    <small>
                        %= image_tag(post.user.avatar.tiny.url) if post.user.avatar? %>
                        submitted %= time_ago_in_words(post.created_at) %> ago by
                        %= post.user.name %><br />
                        %= post.comments.count %> Comments
                    </small>
                </div>
            </div>
            
        % end %>
        -->
        <%= render @posts %>
        
        <!--
            Checkpoint #45 - Pagination
            
            Make the change to the topics#show view that will paginate its list
            of posts. Review your changes on localhost. 'will_paginate' will
            continue to make new pages for every ten topics / posts created.
        -->
        <%= will_paginate @posts %>
    </div>
    <div class="col-md-4">
        <% if policy(Post.new).create? %>
            <!--
                Checkpoint #40 - Topics and Posts
                
                In 'app/views/topics/show.html.erb', we linked to
                'new_post_path(@post)'. As our 'rake routes' output shows, this
                helper is no longer available. (In fact, if you vist a topic's
                'show' page, you'll see a 'NoMethodError' pointing to this fact).
                Instead, we need to reference the 'new_topic_post'.
                
                &lt;%= link_to "New Post", new_post_path(@topic), class: "btn btn-success' %&gt;
            -->
            <%= link_to "New Post", new_topic_post_path(@topic), class: 'btn btn-success' %>
        <% end %>

        <!--
            Checkpoint #51 - Destroy
            
            Now that we have a destroy method in our controller, let's update
            the 'topics#show' view to provide a UI to delete a topic.
        -->
        <% if policy(@topic).destroy? %>
            <%= link_to "Delete Topic", @topic, method: :delete, class: 'btn btn-danger', data: { confirm: 'Are you sure you want to delete this topic?' } %>
        <% end %>
   </div>
</div>