config/routes.rb
Rails.application.routes.draw do
    # Checkpoint #46 - Comments
    #
    # Nest the comments resource under 'resources :post's in 'routes.rb.'' You
    # only have one comment action for now, create, so only create the routes
    # that you need.
    #
    # Hint: Use only: instead of except.
    #
    # By nesting comments inside of 'posts', they'll be nested inside 'topics'
    # as well. As the 'create' url, '/topics/:topic_id/posts/:post_id/comments',
    # suggests, this "deep nesting" can get complicated, and we should refactor
    # it.
    #
    # Commmented out this next line, since keeping it forms a redundancy with
    # the 'resources :comments, only: [:new, :create]' statement below.
    # get 'comments/:new'

  devise_for :users
  
  # Checkpoint #41 - Interlude
  #
  # To make changing user's name possible, we've added a second form under the
  # "Edit personal information" heading. To make it work we also need to modify
  # the routes and make a dedicated UsersController. Open config/routes.rb file
  # and add the following line below the devise_for :users line.
  
  # Checkpoint #58 - Public Profiles
  #
  # You'll only run into this error (the routing error generated afer initially creating 'profiles_spec.rb) if you have resources :users, only: [:update] in your routes file. If you just have resources :users, don't worry if you didn't see the above.
  #resources :users, only: [:update]
  #
  # Checkpoint #59 - Popular Posts
  #
  # While we're thinking about popular posts, let's build a way to display the top Bloccit users.
  #
  #resources :users, only: [:show, :update]
  resources :users, only: [:show, :update, :index]
  
  # Checkpoint #33 - CRUD
  #
  # "We'll remove those in favor of a more succinct way of creating 'Post'
  # routes. Call the 'resources' method, and pass it a sybmol. By doing this
  # you instruct Rails to create routes for every CRUD action."
  #
  # get 'posts/index'
  # get 'posts/show'
  # get 'posts/new'
  # get 'posts/edit'

  # Mentor feedback:
  #   Delete line 15 (posts are nested under topics now).
  #
  # Question: Why does not the checkpoint explicitly remove or comment out
  # 'resources :posts'?
  #
  # resources :posts
  
  # Checkpoint #40 - Topics and Posts
  #
  # The four statements below were automatically generating by the following
  # command executed in the IRB:
  #
  #     'rails g controller topics index new show edit'
  #
  # get 'topics/index'
  # get 'topics/new'
  # get 'topics/show'
  # get 'topics/edit'
  #
  # However, these are commented out in favor of the shortcut that follows.
  # resources :topics
  # By calling 'resources :posts' in the 'resources :topics' block, you are
  # instructing Rails to create nested routes. Review your new routes by
  # running 'rake routes | grep post'.
  # resources :topics do
    # resources :posts, except: [:index]
    #
    # Checkpoint #46 - Comments
    #
    # Nest the comments resource under 'resources :post's in 'routes.rb.'' You
    # only have one comment action for now, create, so only create the routes
    # that you need.
    #
    # Hint: Use only: instead of except.
    #
    # By nesting comments inside of 'posts', they'll be nested inside 'topics'
    # as well. As the 'create' url, '/topics/:topic_id/posts/:post_id/comments',
    # suggests, this "deep nesting" can get complicated, and we should refactor
    # it.
    # resources :posts, except: [:index] do
      # Checkpoint #51 - Destroy
      #
      # Go back to localhost and try to delete a comment. Did you receive an error? (You should have!) If so, try to troubleshoot it on your own before reading on.
      #
      # The error was raised because you have not created a proper route for destroying comments. Open 'routes.rb' and modify the 'resources :comments' declaration to include 'destroy'.
      #
      # resources :comments, only: [:create]
      #resources :comments, only: [:create, :destroy]
    # end
    
    # Assignment #51 - Destroy
    #
    # As the Rails Guide to Routing makes clear, deep route nesting can "quickly become cumbersome". It is cumbersome in a number of ways:
    #
    # - In 'CommentsController' we separately initialize '@topic', '@post' and '@comment'. We do so because the IDs are in the params hash. However, this is unnecessary because we can find the topic and post from the comment. Furthermore, what would happen if we navigated to '/topics/:topic_id/posts/:id' where the post does not belong to the topic? What would happen if we deleted one of the post's comments?
    #
    # - Our routing is cumbersome. In order to route to a comment, we have to know and reference its parent post and topic.
    #
    # - We nested our routes too deeply. As a result, our path helpers are confusing. Before, we just had post_path, but now we have '[@topic, @post, comment]'', or its unintuitive route, 'topic_post_comment_path'.
    #
    # To solve these issues, implement "shallow nesting".
    #
    # Change your routes file to reflect only the primary relationships.
    #
    # Note the 'only: []'' in the top-level post resources line. This is because we don't want to create any '/posts/:id' routes, just 'posts/:post_id/comments'.
  # end
    resources :topics do
      # Checkpoint #59 - Popular Posts
      #
      # Let's move our post views and controllers so they're nested under topics. Make the following directory changes:
      #   - app/controllers/posts_controller.rb -> app/controllers/topics/posts_controller.rb
      #   - app/views/posts/_form.html.erb -> app/views/topics/posts/_form.html.erb
      #   - app/views/posts/edit.html.erb -> app/views/topics/posts/edit.html.erb
      #   - app/views/posts/new.html.erb -> app/views/topics/posts/new.html.erb
      #   - app/views/posts/show.html.erb -> app/views/topics/posts/show.html.erb
      #
      #resources :posts, except: [:index]
      resources :posts, except: [:index], controller: 'topics/posts'
    end
    
    # Checkpoint #59 - Popular Posts
    #
    # The '/app/controllers/posts_controller.rb' 'index' action and the 'app/views/posts/index.html.erb' view combination does not have a route -- let's add it. Because we already have a top-level :posts resource -- without any actions -- we can just add :index to that resource declaration.
    #
    #resources :posts, only: [] do
    resources :posts, only: [:index] do
      resources :comments, only: [:create, :destroy]

      # Checkpoint #55 - Favoriting
      #
      # Notice we didn't specify any views - that is because this controller won't have any normal views. We'll define create and destroy actions, which aren't associated with GET requests, and so have no views. Add the required routes for create and destroy to routes.rb.
      resources :favorites, only: [:create, :destroy]
      
      # Checkpoint #53 - Voting
      #
      # In the voter partial, we stubbed out the destination URL in the link_to methods, but obviously we'll need to update this so the vote links actually do something. Votes are different than topics or posts, because they do not need a complete RESTful resource. In other words, there are no forms or specific views for votes, only the links in the voter partial. This means that our best option is to create a couple of routes manually in 'routes.rb'.
      #
      # These lines set up POST routes at the URL 'posts/:id/up-vote' and 'posts/:id/down-vote'. The as key-value pairs at the end stipulate the method names which will be associated with these routes: 'up_vote_path' and 'down_vote_path'.
      post 'up/vote' => 'votes#up_vote', as: :up_vote
      post 'down/vote' => 'votes#down_vote', as: :down_vote
    end
    
  # Checkpoint #33 - CRUD
  #
  # "Notice that we also removed the get 'welcome/index', because we've
  # declared the 'index' view as 'root'. We also cleaned up the 'about'
  # route, by allowing a user to type '/about' rather than /welcome/about'."
  #
  # get 'welcome/index'
  get 'about' => 'welcome#about'
  
  # I commented this out, since it did not appear in this checkpoint.
  # get 'welcome/contact'
  
  root to: 'welcome#index'
end

app/controllers/posts_controller.rb
# Checkpoint #59 - Popular Posts
#
# Now that we've nested the rest of our post views under topics, let's create the top-level Posts controller and routes.
#
# Notice that we are using the visible_to scope to handle public / private posts based on the current_user object.
#
# Also take note of the "created_at > ?", 7.days.ago syntax. This both lets us use the simple Ruby date syntax and is a countermeasure against SQL Injection.
class PostsController < ApplicationController
    def index
        @posts = Post.visible_to(current_user).where("posts.created_at > ?", 7.days.ago).paginate(page: params[:page], per_page: 10)
    end
end

app/controllers/topics/posts_controller.rb
# Checkpoint #59 - Popular Posts
#
# Since we've moved the posts controller under topics and changed the routes, we'll need to modify the class declaration in app/controllers/topics/posts_controller.rb.
#
# Topics::PostsController instructs the controller where to find the appropriate views to invoke. See the Admin::UserPermissions example in the Rails Guide we linked to above.
#
#class PostsController < ApplicationController
class Topics::PostsController < ApplicationController
  # Checkpoint #40 - Topics and Posts
  #
  # From 'routes.rb':
  #     However, these are commented out in favor of the shortcut that follows.
  #     resources :topics
  #     By calling 'resources :posts' in the 'resources :topics' block, you are
  #     instructing Rails to create nested routes. Review your new routes by
  #     running 'rake routes | grep post'.
  #
  #     resources :topics do
  #       resources :posts, except: [:index]
  #     end
  #
  # You may notice that there's no long a Post route for 'index'. This is
  # because the 'posts/index.html.erb' is no longer needed. All posts will be
  # displayed with respect to a Topic now, so 'posts#index' serves no purpose.
  # Remove the 'index' action from the 'posts_controller.rb', and delete
  # 'app/views/posts/index.html.erb'. You can remove it and stage the removal
  # at once by typing 'git rm app/views/posts/index.html.erb'.
  #
=begin  
  #def index
    # Checkpoint #33 - CRUD
    #
    # "To show dynamic data from the Bloccit database, you'll need to modify
    # the 'index' method in 'post_controller.rb'. In the 'posts_controller.rb',
    # add the following to the 'index' method."
    @posts = Post.all
    
    # Checkpoint #39 - Authorization
    authorize @posts
  end
=end

  def show
    # Checkpoint #46 - Comments
    #
    # View changes:
    #   - You'll need to show comments associated with a post, so modify the
    #     posts_controller to provide the requisite instance variable to
    #     'posts/show.html.erb'.
    #@comment = @post.comments.find(params[:id])

    # Checkpoint #33 - CRUD
    #
    # "...before we update the view, let's go back to 'posts_controller.rb" and
    # update the 'show' method:"
    #
    # The 'show' method declares an instance variable names '@post' and assigns
    # it to the return of 'Post.find(params[:id])'. As you saw before, the
    # 'find' method is an Active Record method that takes an object 'id' as an
    # argument.
    #
    # "The 'PostsController' does not automatically know which post a user
    # clicked. This information has to be extracted from the request made when
    # the link was clicked. Rails controllers parse this request information
    # into a 'params' hash available in the controller and its associated
    # views."
    #
    
    # Checkpoint #40 - Topics and Posts
    #
    # In 'app/views/posts/show.html.erb' we have the statement
    #
    #     '<%= link_to "Edit", edit_topic_post_path(@topic, @post), class: 'btn btn-success' %>'
    #
    # '@topic' is being used to generate a valid URL, but that variable does
    # not exist yet in this view. We add the '@topic' variable here.
    @topic = Topic.find(params[:topic_id])
    
    # Checkpoint #46 - Comments
    #
    # Given the nesting structure, change this here to reflect the following
    # URL: '/topics/:topic_id/posts/:post_id/comments'
    #
    # @post = Post.find(params[:id])
    @post = @topic.posts.find(params[:id])
    @comment = Comment.new
    @comments = @post.comments
  end
  
  def create
    # Checkpoint #40 - Topics and Posts
    @topic = Topic.find(params[:topic_id])
    
    # Checkpoint #41 - Interlude
    #
    # Apply DRY.
    # @post = Post.new(params.require(:post).permit(:title, :body))
    @post = Post.new(post_params)
    
    # Checkpoint #38 - Associations
    @post.user = current_user
    
    # Checkpoint #40 - Topics and Posts
    @post.topic = @topic
    
    # Checkpoint #39 - Authorization
    # 
    # We need to restrict 'posts#create', for when the 'posts#new' form is
    # submitted. We use 'authorize()' to check restrictions on the '@post'
    # about to be saved.
    authorize @post
    
    # Checkpoint #35 - More CRUD
    # raise # This will short-circuit the method
    if @post.save
      # Checkpoint #54 - Mocking with RSpec
      #
      # Anywhere we create a post, we must also call create_vote on it. Some simple text searching for Post.create and post.save returns two relevant results outside of our specs, the posts_controller and our seeds file.
      @post.create_vote
      
      flash[:notice] = "Post was saved."
      
      # Checkpoint #40 - Topics and Posts
      #
      # redirect_to @post
      redirect_to [@topic, @post]
    else
      flash[:error] = "There was an error saving the post. Please try again."
      render :new
    end
  end

  def new
    # Checkpoint #40 - Topics and Posts
    @topic = Topic.find(params[:topic_id])
    @post = Post.new
    @comment = @post.comments
    
    # Checkpoint #39 - Authorization
    #
    # 'authorize()' will check the policy on new post resources. If it's
    # satisfied (in this case, if a user is present), it will let the
    # rendering continue. If not (if no user is present), it'll throw an
    # exception.
    #
    # We have access to this 'authorize' method because we included 'Pundet'
    # in 'ApplicationController', from which the 'PostController' inherits.
    authorize @post
    
    # Assignment #46 - Comments
    #
    # If you try to create a comment without first signing in, you'll encounter a no method 'id' for NilClass error. This error is thrown because current_user is nil when you're not signed in, and comment creation attempts to extract an id from this nil object.
    #   - Use CommentPolicy in PostsController and CommentsController to authorize your comments.
    authorize @comment
  end

  def edit
    # Checkpoint #40 - Topics and Posts
    @topic = Topic.find(params[:topic_id])
    
    # Checkpoint #35 - More CRUD
    @post = Post.find(params[:id])
    
    # Checkpoint #39 - Authorization
    #
    # Call authorize after the objects you've authorized have been defined.
    authorize @post
  end
  
  def update
    # Checkpoint #35 - More CRUD
    @post = Post.find(params[:id])
    @topic = Topic.find(params[:topic_id])
    
    # Checkpoint #39 - Authorization
    #
    # Call authorize after the objects you've authorized have been defined.
    authorize @post
    
    # Checkpoint #41 - Interlude
    #
    # Apply DRY.
    # if @post.update_attributes(params.require(:post).permit(:title, :body))
    if @post.update_attributes(post_params)
      flash[:notice] = "Post was updated."
      redirect_to [@topic, @post]
    else
      flash[:error] = "There was an error saving the post. Please try again."
      render :edit
    end
  end
  
  # Checkpoint #51 - Destroy
  #
  # Open PostsController and add a destroy action
  def destroy
    @topic = Topic.find(params[:topic_id])
    @post = Post.find(params[:id])
    
    authorize @post
    
    if @post.destroy
      flash[:notice] = "\"#{@post.title}\" was deleted successfully."
      redirect_to @topic
    else
      flash[:error] = "There was an error deleting the post."
      render :show
    end
  end

  # Checkpoint #41 - Interlude
  #
  # Apply DRY.
  private

  def post_params
    params.require(:post).permit(:title, :body)
  end
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/views/topics/posts/_form.html.erb
<!--
    Checkpoint #42 - Validating Posts
    
    The underscore at the beginning of a name lets Rails know that this
    file is a partial.
    
    Note how we render our partial in in the 'edit' and 'new' views:
    
        &lt;%= render partial: 'form', locals: { topic: @topic, post: @post } %gt;

    This tells the 'render' method to paste in the '_form.html.erb' file
    in its current directory, after passing in 'topic' and 'post' as
    local variable. When we write locals: { topic: @topic, post: @post },
    we're telling Rails to render the '_form' view after assigning 'topic'
    and 'post' to equal '@topic' and '@post', respectively. This means, we
    should refer to these local variables, rather than the instance
    variables we used in the 'edit' view here.
    
    Although the partial has access to the @topic and @post instance
    variables, it's a best practice to use local variable in order to
    promote flexibility. We want to be able to render a given partial
    on any page, whether or not it has two instance varabiles with
    those naems.
    
    The partial view is called '_form.html.erb', which is identified
    in the 'render' method by "partial: 'form'". This is a Rails
    convention for partial naming. If we don't follow it, the partial
    will not be found.

&lt;%= form_for [@topic, @post] do |f| %&gt;
-->
<%= form_for [topic, post] do |f| %>
    <% if post.errors.any? %>
        <div class="alert alert-danger">
            <h4>There are <%= pluralize(post.errors.count, "error") %>.</h4>
            <ul>
                <% post.errors.full_messages.each do |msg| %>
                    <li><%= msg %></li>
                <% end %>
            </ul>
        </div>
    <% end %>
    <%= form_group_tag(post.errors[:title]) do %>
        <%= f.label :title %>
        <%= f.text_field :title, class: 'form-control', placeholder: "Enter post title" %>
    <% end %>
    <%= form_group_tag(post.errors[:body]) do %>
        <%= f.label :body %>
        <%= f.text_area :body, rows: 8, class: 'form-control', placeholder: "Enter post body" %>
    <% end %>
    <div class="form-group">
        <%= f.submit "Save", class: 'btn btn-success' %>
    </div>
<% end %>

app/views/topics/posts/edit.html.erb
<!-- Checkpoint #35 - More CRUD
<h1>Posts#edit</h1>
<p>Find me in app/views/posts/edit.html.erb</p> -->

<h1>Edit Post</h1>

<div class="row">
    <div class="col-md-4">
        <p>Guidelines for posts</p>
        <ul>
            <li>Stay on topic.</li>
            <li>Keep it concise.</li>
            <li>Do not cross-post.</li>
        </ul>
    </div>
    <div class="col-md-8">
        <!--
            Checkpoint #42 - Validating Posts
            
            Now that you have some new errors that can be raised by the
            validates methods (see 'post.rb'), change the 'Post' views
            to display these errors when they occur. Since these changes
            affect both the 'new' and 'edit' views, this is a good time
            to demonstrate using partials to make our views DRY.
            
            Partials are fragments of template code, which are used in
            views. Partials are called with the 'render' method. Rendering
            a partial is essentially copying and pasting view code from
            another file.
            
            You've called a partial in 'posts#edit', but currently, this
            partial file doesn't exist. To get this partial render working,
            we need to create the specified 'form' file, and fill it with
            the contents we just cut out.
            
            Note: This checkpoint requires commenting out the code
            added in Checkpoint #40.
        -->
        <!--
            Checkpoint #40 - Topics and Posts
            &lt;%= form_for @post do |f| %&gt;
        -->
        <!--&lt;%= form_for [@topic, @post] do |f| &gt;%
            <div class="form-group">
                &lt;%= f.label :title &gt;%
                &lt;%= f.text_field :title, class: 'form-control', placeholder: "Enter post title" &gt;%
            </div>
            <div class="form-group">
                &lt;%= f.label :body &gt;%
                &lt;%= f.text_area :body, rows: 8, class: 'form-control', placeholder: "Enter post body" &gt;%
            </div>
            <div class="form-group">
                &lt;%= f.submit "Save", class: 'btn btn-success' &gt;%
            </div>
        &lt;% end &gt;%-->

        <div class="row">
            <div class="col-md-4">
                <p>Guidelines for <posts></posts></p>
                <ul>
                    <li>Make sure it rhymes.</li>
                    <li>Don't use the letter "A".</li>
                    <li>The incessant use of hashtags will get you banned.</li>
                </ul>
            </div>
            <div class="col-md-8">
                <%= render partial: 'form', locals: { topic: @topic, post: @post } %>
            </div>
        </div>
    </div>
</div>

app/views/topics/posts/new.html.erb
<!-- Checkpoint #35 - More CRUD
<h1>Posts#new</h1>
<p>Find me in app/views/posts/new.html.erb</p>
-->
<h1>New Post</h1>

<div class="row">
    <div class="col-md-=r4">
        <p>Guidelines for posts</p>
        <ul>
            <li>Make sure it rhymes.</li>
            <li>Don't use the letter "A".</li>
            <li>The incessant use of hastags will get you banned.</li>
        </ul>
    </div>
    <div class="col-md-8">
        <!--
            Checkpoint #42 - Validating Posts

            (See detailed comments on the posts 'edit' view template.
        -->
        <!--
            Checkpoint #40 - Topics and Posts
            
            &lt;%= form_for @post do |f| %&gt;
        -->
        <!-- &lt;%= form_for [@topic, @post] do |f| &gt;%
            <div class="form-group">
                &lt;%= f.label :title &gt;%
                &lt;%= f.text_field :title, class: 'form-control', placeholder: "Enter post title" &gt;%
            </div>
            <div class="form-group">
                &lt;%= f.label :body &gt;%
                &lt;%= f.text_area :body, rows: 8, class: 'form-control', placeholder: "Enter post body" &gt;%
            </div>
            <div class="form-group">
                &lt;%= f.submit "Save", class: 'btn-btn-success' &gt;%
            </div>
        &lt;% end &gt;% -->
        
        <%= render partial: 'form', locals: { topic: @topic, post: @post } %>
    </div>
</div>

app/views/topics/posts/show.html.erb
    <!--
    When you refresh the page, you should see something like this:
    
    {"action"=>"show", "controller"=>"posts", "id"=>"1"}
    
    ...this hash contains information on which controller we're in, and which
    action. It also has the 'id' of the post on which we clicked (and which is
    encoded in the URL).
-->

<!-- &lt;%= params %&gt; -->
<!--
    Checkpoint #33 - CRUD
    Replace previous code with post-specific code.
-->
<!--
    Checkpoint #43 - Post Markdown
    
<h1>&lt;%= @post.title %&gt;</h1>
-->
<!-- <h1>%= markdown_to_html @post.title %></h1> -->

<!-- Checkpoint #35 - More CRUD, the 'link_to statement -->
<!-- Checkpoint #39 - Authorization, the surrouding 'if' -->
<!--
    Checkpoint #40 - Topics and Posts
    
    Add (Twitter) Bootstrap CSS.
    Modified the 'link_to' statement.
&lt;% if policy(@post).edit? %&gt;
    &lt;%= link_to "Edit", edit_post_path(@post), class: 'btn btn-success' %&gt;
&lt;% end %&gt;
<p>&lt;%= @post.body %&gt;</p>
-->

<!--
    Checkpoint #46 - Comments
    
    View changes:
        - Create a '_comment.html.erb' partial in the comments directory. Use it
          in the 'posts#show' view to show the body of each comment already
          associated with the post. Whereas our above form partial should render
          the form for submitting a new comment, this comment partial should
          render the relevant information for a single preexisting comment
          associated with our '@post'. Because this partial renders a single
          comment, we need to call it multiple times, rendering a partial for
          each comment in @comments. This is a good candidate for an each loop.
-->
<div class="row">
    <div class="col-md-8">
        <!--
            We have our voter partial, so let's think about where we should call render. Users should be able to vote on each post, so we need to render our voter partial wherever we show posts. There are two places we do that - 'views/posts/show.html.erb' and 'app/views/topics/show.html.erb'. Open 'app/views/posts/show.html.erb' and add the call to render.
            
            Because the partial has access to the '@post' variable, we don't technically need to pass it here. Other views where we would like to incorporate this partial might not have an identical '@post' variable, however, so it's a much better idea to pass 'post' in explicitly, rather than implicitly expect a '@post'. This is why we made the partial we created reference 'post', not '@post'.
        --->
        <%= render partial: 'votes/voter', locals: { post: @post } %>
        
        <!---
            Checkpoint #53 - Voting
            
            Go back to 'app/views/posts/show.html.erb' and move the '<h1>' containing 'post.title' directly under the call to render our voter partial.
        --->
        <h1><%= markdown_to_html @post.title %></h1>
        
        <!--
            Checkpoint #44 - Uploading Images
            
            Open posts#show and add a user image to a post.
        -->

        <small>
            <%= image_tag(@post.user.avatar.tiny.url) if @post.user.avatar? %>
            submitted <%= time_ago_in_words(@post.created_at) %> ago by
            <%= @post.user.name %>
        </small>

        <!--
            Checkpoint #43 - Post Markdown

        <p>%= @post.body %></p>
        -->    

        <p><%= markdown_to_html @post.body %></p>
    </div>
    <div class="col-md-4">
        <% if policy(@post).edit? %>
            <%= link_to "Edit", edit_topic_post_path(@topic, @post), class: 'btn btn-success' %>
        <% end %>
    
        <!--
            Checkpoint #51 - Destroy
            
            Modify 'posts#show' to add a 'link_t' for deletion.
            
            Notice that we must supply an array of instance variables ([@topic, @post]) to the 'link_to' method because posts are nested under topics.
        -->
        <% if policy(@post).destroy? %>
            <%= link_to "Delete Post", [@topic, @post], method: :delete, class: 'btn btn-danger', data: { confirm: "Are you sure you want to delete this post?" } %>
        <% end %>
        
        <!--
            Checkpoint #53 - Voting
            
            If you refresh the page, you'll notice that posts#show is looking better. But it would be nice to display the score of the post more prominently. Remember that you added a few methods to 'post.rb'. Let's use them to make the show view even nicer. In 'app/views/posts/show.html.erb', add the following.
        -->
        <div>
            <h3><%= pluralize(@post.points, 'point') %></h3>
            <small>
                <%= pluralize(@post.up_votes, 'up vote') %>
                <%= pluralize(@post.down_votes, 'down vote') %>
            </small>
        </div>
        
        <!--
            Checkpoint #55 - Favorited
            
            Let's render the '_favorite.html.erb' partial in the posts#show view.
        -->
        <%= render partial: 'favorites/favorite', locals: { post: @post } %>
    </div>
</div>

<h3>Comments:</h3>

<!--
    Assignment #46 - Comments
    
    If you try to create a comment without first signing in, you'll encounter a
    no method 'id' for NilClass error. This error is thrown because current_user
    is nil when you're not signed in, and comment creation attempts to extract
    an id from this nil object.
        - Use CommentPolicy in posts#show to hide the comment form unless a user
          is signed in.

    Dalibor's comment:
        - Use &lt;% if policy(@comment).new? %>

% if @post.user.present? %>
    %= render partial: 'comments/form', locals: {topic: @topic, post: @post, comment: @comment} %>
% end %>
-->

    <!--
        Dalibor's comment:
        
        Use the policy, not the:

        % if @post.user.present? %>
            %= render partial: 'comments/form', locals: {topic: @topic, post: @post, comment: @comment} %>
        % end %>
    -->
    <!--
        Dalibor's comment:
            - Use &lt;% if policy(@comment).new? %> instead of &lt;% @post.user.present? %>
    -->
<!--
% if policy(@comment).new? %>
    %= render partial: 'comments/form', locals: {topic: @topic, post: @post, comment: @comment} %>
% end %>
-->

<!--
    Checkpoint #59 - Popular Posts
    
    There's also a subtle change we'll need to make in app/views/topics/posts/show.html.erb.
    
    This change is due to Rails organizational conventions. When Rails sees render @comments, it looks for a _comment partial in the parent directory of the view where it's called. But now the parent directory of the current view is topics, which does not contain that partial -- so we must specify the path to the partial to render for each item in the collection.
    
    %= render @comments %>
    
    Note: The next line, which is consistent with the Checkpoint #59 - Popular Posts instructions, already existed from a past checkpoint.

    Checkpoint #61 - Creating with Ajax
    
    To add a comment to the top of a list, we'll use the jQuery prepend method. To call prepend, we'll need something to prepend the comment to. Open posts#show and add a div around the comments collection and also around the new comment form.
%= render partial: 'comments/comment', collection: @comments %>
-->
<div class='js-comments'>
    <%= render partial: 'comments/comment', collection: @comments %>
</div>
<div class='new-comment'>
    <%= render 'comments/form' %>
</div>