config/routes.rb
Rails.application.routes.draw do
    # Checkpoint #46 - Comments
    #
    # Nest the comments resource under 'resources :post's in 'routes.rb.'' You
    # only have one comment action for now, create, so only create the routes
    # that you need.
    #
    # Hint: Use only: instead of except.
    #
    # By nesting comments inside of 'posts', they'll be nested inside 'topics'
    # as well. As the 'create' url, '/topics/:topic_id/posts/:post_id/comments',
    # suggests, this "deep nesting" can get complicated, and we should refactor
    # it.
    #
    # Commmented out this next line, since keeping it forms a redundancy with
    # the 'resources :comments, only: [:new, :create]' statement below.
    # get 'comments/:new'

  devise_for :users
  
  # Checkpoint #41 - Interlude
  #
  # To make changing user's name possible, we've added a second form under the
  # "Edit personal information" heading. To make it work we also need to modify
  # the routes and make a dedicated UsersController. Open config/routes.rb file
  # and add the following line below the devise_for :users line.
  
  # Checkpoint #58 - Public Profiles
  #
  # You'll only run into this error (the routing error generated afer initially creating 'profiles_spec.rb) if you have resources :users, only: [:update] in your routes file. If you just have resources :users, don't worry if you didn't see the above.
  #resources :users, only: [:update]
  #
  # Checkpoint #59 - Popular Posts
  #
  # While we're thinking about popular posts, let's build a way to display the top Bloccit users.
  #
  #resources :users, only: [:show, :update]
  resources :users, only: [:show, :update, :index]
  
  # Checkpoint #33 - CRUD
  #
  # "We'll remove those in favor of a more succinct way of creating 'Post'
  # routes. Call the 'resources' method, and pass it a sybmol. By doing this
  # you instruct Rails to create routes for every CRUD action."
  #
  # get 'posts/index'
  # get 'posts/show'
  # get 'posts/new'
  # get 'posts/edit'

  # Mentor feedback:
  #   Delete line 15 (posts are nested under topics now).
  #
  # Question: Why does not the checkpoint explicitly remove or comment out
  # 'resources :posts'?
  #
  # resources :posts
  
  # Checkpoint #40 - Topics and Posts
  #
  # The four statements below were automatically generating by the following
  # command executed in the IRB:
  #
  #     'rails g controller topics index new show edit'
  #
  # get 'topics/index'
  # get 'topics/new'
  # get 'topics/show'
  # get 'topics/edit'
  #
  # However, these are commented out in favor of the shortcut that follows.
  # resources :topics
  # By calling 'resources :posts' in the 'resources :topics' block, you are
  # instructing Rails to create nested routes. Review your new routes by
  # running 'rake routes | grep post'.
  # resources :topics do
    # resources :posts, except: [:index]
    #
    # Checkpoint #46 - Comments
    #
    # Nest the comments resource under 'resources :post's in 'routes.rb.'' You
    # only have one comment action for now, create, so only create the routes
    # that you need.
    #
    # Hint: Use only: instead of except.
    #
    # By nesting comments inside of 'posts', they'll be nested inside 'topics'
    # as well. As the 'create' url, '/topics/:topic_id/posts/:post_id/comments',
    # suggests, this "deep nesting" can get complicated, and we should refactor
    # it.
    # resources :posts, except: [:index] do
      # Checkpoint #51 - Destroy
      #
      # Go back to localhost and try to delete a comment. Did you receive an error? (You should have!) If so, try to troubleshoot it on your own before reading on.
      #
      # The error was raised because you have not created a proper route for destroying comments. Open 'routes.rb' and modify the 'resources :comments' declaration to include 'destroy'.
      #
      # resources :comments, only: [:create]
      #resources :comments, only: [:create, :destroy]
    # end
    
    # Assignment #51 - Destroy
    #
    # As the Rails Guide to Routing makes clear, deep route nesting can "quickly become cumbersome". It is cumbersome in a number of ways:
    #
    # - In 'CommentsController' we separately initialize '@topic', '@post' and '@comment'. We do so because the IDs are in the params hash. However, this is unnecessary because we can find the topic and post from the comment. Furthermore, what would happen if we navigated to '/topics/:topic_id/posts/:id' where the post does not belong to the topic? What would happen if we deleted one of the post's comments?
    #
    # - Our routing is cumbersome. In order to route to a comment, we have to know and reference its parent post and topic.
    #
    # - We nested our routes too deeply. As a result, our path helpers are confusing. Before, we just had post_path, but now we have '[@topic, @post, comment]'', or its unintuitive route, 'topic_post_comment_path'.
    #
    # To solve these issues, implement "shallow nesting".
    #
    # Change your routes file to reflect only the primary relationships.
    #
    # Note the 'only: []'' in the top-level post resources line. This is because we don't want to create any '/posts/:id' routes, just 'posts/:post_id/comments'.
  # end
    resources :topics do
      # Checkpoint #59 - Popular Posts
      #
      # Let's move our post views and controllers so they're nested under topics. Make the following directory changes:
      #   - app/controllers/posts_controller.rb -> app/controllers/topics/posts_controller.rb
      #   - app/views/posts/_form.html.erb -> app/views/topics/posts/_form.html.erb
      #   - app/views/posts/edit.html.erb -> app/views/topics/posts/edit.html.erb
      #   - app/views/posts/new.html.erb -> app/views/topics/posts/new.html.erb
      #   - app/views/posts/show.html.erb -> app/views/topics/posts/show.html.erb
      #
      #resources :posts, except: [:index]
      resources :posts, except: [:index], controller: 'topics/posts'
    end
    
    # Checkpoint #59 - Popular Posts
    #
    # The '/app/controllers/posts_controller.rb' 'index' action and the 'app/views/posts/index.html.erb' view combination does not have a route -- let's add it. Because we already have a top-level :posts resource -- without any actions -- we can just add :index to that resource declaration.
    #
    #resources :posts, only: [] do
    resources :posts, only: [:index] do
      resources :comments, only: [:create, :destroy]

      # Checkpoint #55 - Favoriting
      #
      # Notice we didn't specify any views - that is because this controller won't have any normal views. We'll define create and destroy actions, which aren't associated with GET requests, and so have no views. Add the required routes for create and destroy to routes.rb.
      resources :favorites, only: [:create, :destroy]
      
      # Checkpoint #53 - Voting
      #
      # In the voter partial, we stubbed out the destination URL in the link_to methods, but obviously we'll need to update this so the vote links actually do something. Votes are different than topics or posts, because they do not need a complete RESTful resource. In other words, there are no forms or specific views for votes, only the links in the voter partial. This means that our best option is to create a couple of routes manually in 'routes.rb'.
      #
      # These lines set up POST routes at the URL 'posts/:id/up-vote' and 'posts/:id/down-vote'. The as key-value pairs at the end stipulate the method names which will be associated with these routes: 'up_vote_path' and 'down_vote_path'.
      post 'up/vote' => 'votes#up_vote', as: :up_vote
      post 'down/vote' => 'votes#down_vote', as: :down_vote
    end
    
  # Checkpoint #33 - CRUD
  #
  # "Notice that we also removed the get 'welcome/index', because we've
  # declared the 'index' view as 'root'. We also cleaned up the 'about'
  # route, by allowing a user to type '/about' rather than /welcome/about'."
  #
  # get 'welcome/index'
  get 'about' => 'welcome#about'
  
  # I commented this out, since it did not appear in this checkpoint.
  # get 'welcome/contact'
  
  root to: 'welcome#index'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bloccit</title>
    <meta name="viewport" contgent="width=device-width, initial-scale=1"/>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <div class="container">
      <ul class="nav nav-tabs">
        <!--
          The Rails 'link_to' method returns a qualified HTML anchor tag. For example,
        
              link_to "Home", welcome_index_path
        
          renders
        
              <a href="/welcome/index">Home</a>
        -->
        
        <!--
          Checkpoint #33 - CRUD
          
          "...change the two link_to lines:
        <li>&lt;%= link_to "Bloccit", welcome_index_path %&gt;</li>
        <li>&lt;%= link_to "About", welcome_about_path %&gt;</li>
        -->
        <li><%= link_to "Bloccit", root_path %></li>
        <li><%= link_to "About", about_path %></li>
      </ul>
      
      <!-- Checkpoint #35 - More CRUD -->
      <% if flash[:notice] %>
        <div class="alert alert-success">
          <button type="button" class="close" data-dismiss="alert">&times;</button>
          <%= flash[:notice] %>
        </div>
      <% elsif flash[:error] %>
        <div class="alert alert-danger">
          <button type="button" class="close" data-dismiss="alert">&times;</button>
          <%= flash[:error] %>
        </div>
      <% elsif flash[:alert] %>
        <div class="alert alert-warning">
          <button type="button" class="close" data-dismiss="alert">&times;</button>
          <%= flash[:alert] %>
        </div>
      <% end %>
      
      <!--
        Checkpoint #37 - Authentication Continued
        
        See the 'Current User' section.
      -->
      <div class="pull-right user-info">
        <% if current_user %>
          <!--
            Checkpoint #44 - Uploading Images
            
            Let's modify our header nav so it displays user images if available.
          -->
          <%=   image_tag(current_user.avatar.tiny.url) if current_user.avatar? %>

          <!--
            Checkpoint #40 - Topics and Posts
            
            Update the 'user-info div' to user the 'current_user' name.
            
            Hello &lt;%= current_user.email %&gt;! lt;%= link_to "Sign out", destroy_user_session_path, method: :delete %&gt;
          -->
          
          <!--
            Checkpoint #41 - Interlude
            
            Make the following changes to app/views/layouts/application.html.erb
            
          Hello &lt;%= current_user.name %&gt;! &lt;%= link_to "Sign out", destroy_user_session_path, method: :delete %&gt;
          
            This change creates a link to the signed-in user's profile edit page.
            The link text displays the user's email if the user's name hasn't been
            set.
          -->
          
          <!--
            Checkpoint #58 - Public Profiles
            
            Right now, users can only visit their profiles if they enter the URL. Let's create a nav link that takes users to this page. Open application.html.erb and make the following changes.
            
          Hello %= link_to (current_user.name || current_user.email), edit_user_registration_path %>! %= link_to "Sign out", destroy_user_session_path, method: :delete %>
          
          We're adding a link to the profile page and changing two of our link_to calls to use nested HTML with Bootstrap icons, rather than just link text.
          -->
          Hello <%= link_to (current_user.name || current_user.email), current_user %>!
          
          <%= link_to edit_user_registration_path, clas: 'btn btn-primary btn-sm' do %>
            <span class="glyphicon glyphicon-user"></span>
          <% end %>
          
          <%= link_to destroy_user_session_path, method: :delete, class: 'btn btn-primary btn-sm' do %>
            <span class="glyphicon glyphicon-log-out"></span>
          <% end %>
        <% else %>
          <%= link_to "Sign In", new_user_session_path %> or
          <%= link_to "Sign Up", new_user_registration_path %>
        <% end %>
      </div>
      
      <% if flash[:notice] %>
        <div class="alert alert-success">
          <button type="button" class="close" data-dismiss="alert">&times;</button>
          <%= flash[:notice] %>
        </div>
      <% elsif flash[:error] %>
        <div class="alert alert-danger">
          <button type="button" class="close" data-dismiss="alert">&times;</button>
          <%= flash[:error] %>
        </div>
      <% elsif flash[:alert] %>
        <div class="alert alert-warning" >
          <button type="button" class="close" data-dismiss="alert">&times;</button>
        </div>
      <% end %>
    
      <%= yield %>
    </div>
  </body>
</html>